package ai.qubere.document.agent.document.storage;

import ai.qubere.document.agent.document.parser.DocumentParserException;
import ai.qubere.document.agent.document.parser.ParserErrorCode;
import ai.qubere.document.agent.document.processing.DocumentBytesSource;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;
import java.util.regex.Pattern;

/**
 * A local-disk implementation of both {@link DocumentBytesWriter} and {@link DocumentBytesSource}:
 * one directory per document id, holding the raw bytes plus a small metadata file recording the
 * original filename and MIME type (which {@link DocumentBytesSource#filename(String)} and
 * {@link DocumentBytesSource#mimeType(String)} need but the bytes alone do not carry).
 * <p>
 * A real, production-viable option for single-instance deployments or deployments that mount a
 * shared volume across instances (e.g. an NFS/EFS-backed path) — not merely a local-dev stub. It is
 * <strong>not</strong> a port of the TypeScript source's {@code loadDocumentBytes.ts}, which reads
 * from a sibling Next.js app's own quarantine directories, a database-recorded object-storage URL,
 * and a database {@code rawContent} column, in that specific order — none of which this module owns
 * or has any reason to replicate, since this framework's agents are deliberately separate services
 * that receive documents through their own API rather than reaching into another application's
 * database and filesystem layout. What <em>is</em> preserved from the source is the shape of the
 * safety guard: a validated document id and a filename reduced to its basename, with the resolved
 * path asserted to stay inside the configured root, so neither caller-supplied value can escape the
 * storage directory.
 * <p>
 * Cloud object storage (S3 / GCS / Azure Blob) is a deliberately deferred extension, not built here
 * — this framework has no existing object-storage abstraction to build on, and inventing one
 * without a live bucket/credentials to verify against would be exactly the kind of speculative
 * infrastructure this project avoids elsewhere (see the same reasoning already recorded for the
 * deferred Kafka/RabbitMQ/SQS async-queue adapters). A deployment that needs it can supply its own
 * {@link DocumentBytesSource} (and, if it should accept uploads directly, {@link DocumentBytesWriter})
 * bean; {@code document-agent.storage.type=local-disk} remains the default, real, testable option.
 */
public class LocalDiskDocumentStorage implements DocumentBytesWriter, DocumentBytesSource {

    /** Document ids are generated by this service (see the submission controller); this is a
     *  defense-in-depth guard against a caller-supplied id, not the primary safety mechanism. */
    private static final Pattern SAFE_DOCUMENT_ID = Pattern.compile("^[A-Za-z0-9_-]{1,128}$");

    private static final String CONTENT_FILE_NAME = "content.bin";
    private static final String METADATA_FILE_NAME = "metadata.properties";
    private static final String META_FILENAME_KEY = "fileName";
    private static final String META_MIME_TYPE_KEY = "mimeType";

    private final Path root;
    private final long maxFileSizeBytes;

    public LocalDiskDocumentStorage(DocumentStorageProperties.LocalDisk properties) {
        this.root = Path.of(properties.getRootDir()).toAbsolutePath().normalize();
        this.maxFileSizeBytes = properties.getMaxFileSizeBytes();
        try {
            Files.createDirectories(root);
        } catch (IOException ex) {
            throw new UncheckedIOException("Unable to create document storage root directory: " + root, ex);
        }
    }

    @Override
    public void store(String documentId, String fileName, String mimeType, byte[] bytes) {
        if (bytes == null || bytes.length == 0) {
            throw new IllegalArgumentException("Document bytes must not be empty.");
        }
        if (bytes.length > maxFileSizeBytes) {
            throw new IllegalArgumentException(
                    "Document is " + bytes.length + " bytes, exceeding the configured limit of " + maxFileSizeBytes + " bytes.");
        }
        Path documentDir = resolveDocumentDir(documentId);
        try {
            Files.createDirectories(documentDir);
            Files.write(documentDir.resolve(CONTENT_FILE_NAME), bytes, StandardOpenOptionsCreateTruncate());
            writeMetadata(documentDir, safeFileName(fileName), safeMimeType(mimeType));
        } catch (IOException ex) {
            throw new UncheckedIOException("Unable to store document " + documentId, ex);
        }
    }

    @Override
    public byte[] loadBytes(String documentId) {
        Path contentFile = resolveDocumentDir(documentId).resolve(CONTENT_FILE_NAME);
        if (!Files.isRegularFile(contentFile)) {
            throw unavailable(documentId);
        }
        try {
            return Files.readAllBytes(contentFile);
        } catch (IOException ex) {
            throw unavailable(documentId);
        }
    }

    @Override
    public String filename(String documentId) {
        return readMetadata(documentId).getProperty(META_FILENAME_KEY, "document");
    }

    @Override
    public String mimeType(String documentId) {
        return readMetadata(documentId).getProperty(META_MIME_TYPE_KEY, "application/octet-stream");
    }

    /**
     * Validates {@code documentId} and resolves its storage directory, asserting the result stays
     * inside {@link #root} — the actual traversal guard, independent of the id pattern check above.
     */
    private Path resolveDocumentDir(String documentId) {
        if (documentId == null || !SAFE_DOCUMENT_ID.matcher(documentId).matches()) {
            throw new IllegalArgumentException("Invalid document id: " + documentId);
        }
        Path candidate = root.resolve(documentId).normalize();
        if (!candidate.startsWith(root)) {
            throw new IllegalArgumentException("Invalid document id: " + documentId);
        }
        return candidate;
    }

    private String safeFileName(String fileName) {
        if (fileName == null || fileName.isBlank()) {
            return "document";
        }
        // fileName is stored as metadata only, never used to build a filesystem path itself (the
        // content file always has a fixed name) -- basename-reduction still applied so nothing
        // resembling a path ever ends up recorded.
        String basename = Path.of(fileName).getFileName().toString();
        return basename.isBlank() ? "document" : basename;
    }

    private String safeMimeType(String mimeType) {
        return (mimeType == null || mimeType.isBlank()) ? "application/octet-stream" : mimeType;
    }

    private void writeMetadata(Path documentDir, String fileName, String mimeType) throws IOException {
        Properties properties = new Properties();
        properties.setProperty(META_FILENAME_KEY, fileName);
        properties.setProperty(META_MIME_TYPE_KEY, mimeType);
        Path metadataFile = documentDir.resolve(METADATA_FILE_NAME);
        try (var writer = Files.newBufferedWriter(metadataFile, StandardCharsets.UTF_8)) {
            properties.store(writer, "Qubere document metadata");
        }
    }

    private Properties readMetadata(String documentId) {
        Path metadataFile = resolveDocumentDir(documentId).resolve(METADATA_FILE_NAME);
        Properties properties = new Properties();
        if (!Files.isRegularFile(metadataFile)) {
            throw unavailable(documentId);
        }
        try (var reader = Files.newBufferedReader(metadataFile, StandardCharsets.UTF_8)) {
            properties.load(reader);
        } catch (IOException ex) {
            throw unavailable(documentId);
        }
        return properties;
    }

    private static java.nio.file.OpenOption[] StandardOpenOptionsCreateTruncate() {
        return new java.nio.file.OpenOption[] {
                java.nio.file.StandardOpenOption.CREATE,
                java.nio.file.StandardOpenOption.TRUNCATE_EXISTING,
                java.nio.file.StandardOpenOption.WRITE
        };
    }

    private static DocumentParserException unavailable(String documentId) {
        return new DocumentParserException(
                ParserErrorCode.SOURCE_FILE_UNAVAILABLE,
                "Document " + documentId + " is not present in local-disk storage.",
                true, null, null
        );
    }
}
