-- Qubere Agent Platform Phase 1 manual DDL for Oracle.
-- Execute manually before running qubere-echo-agent with spring.jpa.hibernate.ddl-auto=validate.
-- Oracle does not support create table if not exists; run once per schema.

create table agent_execution_record (
    execution_id varchar2(64 char) not null,
    agent_id varchar2(128 char) not null,
    agent_version varchar2(64 char) not null,
    tenant_id varchar2(128 char),
    actor_id varchar2(128 char),
    idempotency_key varchar2(128 char),
    workflow_id varchar2(64 char),
    parent_execution_id varchar2(64 char),
    status varchar2(32 char) not null,
    input_json clob,
    output_json clob,
    error_message clob,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint pk_agent_execution_record primary key (execution_id)
);

create index idx_agent_execution_record_workflow
    on agent_execution_record (workflow_id, created_at);

create index idx_agent_execution_record_agent
    on agent_execution_record (agent_id, agent_version);

create index idx_agent_execution_record_tenant
    on agent_execution_record (tenant_id, created_at);

create unique index ux_agent_execution_record_idempotency
    on agent_execution_record (tenant_id, idempotency_key);

create table agent_execution_log (
    id number generated by default as identity not null,
    execution_id varchar2(64 char) not null,
    agent_id varchar2(128 char) not null,
    agent_version varchar2(64 char) not null,
    tenant_id varchar2(128 char),
    actor_id varchar2(128 char),
    correlation_id varchar2(128 char),
    step varchar2(64 char) not null,
    log_level varchar2(16 char) not null,
    message varchar2(1000 char),
    attributes_json clob,
    occurred_at timestamp with time zone not null,
    constraint pk_agent_execution_log primary key (id)
);

create index idx_agent_execution_log_execution
    on agent_execution_log (execution_id, occurred_at);

create index idx_agent_execution_log_tenant
    on agent_execution_log (tenant_id, occurred_at);

create index idx_agent_execution_log_agent
    on agent_execution_log (agent_id, agent_version, occurred_at);
create table agent_tool_call (
    call_id varchar2(64 char) not null,
    execution_id varchar2(64 char) not null,
    tenant_id varchar2(128 char),
    actor_id varchar2(128 char),
    correlation_id varchar2(128 char),
    tool_name varchar2(128 char) not null,
    tool_risk_level varchar2(32 char) not null,
    side_effects varchar2(512 char),
    status varchar2(32 char) not null,
    input_json clob,
    output_summary varchar2(1000 char),
    error_message clob,
    approval_id varchar2(64 char),
    started_at timestamp with time zone not null,
    completed_at timestamp with time zone,
    latency_ms number(19),
    constraint pk_agent_tool_call primary key (call_id)
);

create index idx_agent_tool_call_execution
    on agent_tool_call (execution_id, started_at);

create index idx_agent_tool_call_tenant
    on agent_tool_call (tenant_id, started_at);

create index idx_agent_tool_call_tool
    on agent_tool_call (tool_name, status, started_at);

create table agent_model_usage (
    usage_id varchar2(64 char) not null,
    execution_id varchar2(64 char),
    tenant_id varchar2(128 char),
    actor_id varchar2(128 char),
    correlation_id varchar2(128 char),
    agent_id varchar2(128 char),
    agent_version varchar2(64 char),
    model_provider varchar2(64 char),
    model_name varchar2(128 char),
    prompt_version varchar2(64 char),
    status varchar2(32 char) not null,
    input_tokens number(19),
    output_tokens number(19),
    total_tokens number(19),
    estimated_cost_usd number(19, 6),
    latency_ms number(19),
    error_message clob,
    metadata_json clob,
    started_at timestamp with time zone not null,
    completed_at timestamp with time zone,
    constraint pk_agent_model_usage primary key (usage_id)
);

create index idx_agent_model_usage_execution
    on agent_model_usage (execution_id, started_at);

create index idx_agent_model_usage_tenant
    on agent_model_usage (tenant_id, started_at);

create index idx_agent_model_usage_model
    on agent_model_usage (model_provider, model_name, started_at);
create table agent_tool_audit_event (
    id number generated by default as identity not null,
    execution_id varchar2(64 char) not null,
    tenant_id varchar2(128 char),
    actor_id varchar2(128 char),
    tool_name varchar2(128 char) not null,
    status varchar2(32 char) not null,
    message varchar2(1000 char),
    metadata_json clob,
    occurred_at timestamp with time zone not null,
    constraint pk_agent_tool_audit_event primary key (id)
);

create index idx_agent_tool_audit_execution
    on agent_tool_audit_event (execution_id, occurred_at);

create index idx_agent_tool_audit_tenant
    on agent_tool_audit_event (tenant_id, occurred_at);

create table agent_prompt_template (
    prompt_id varchar2(128 char) not null,
    version varchar2(64 char) not null,
    agent_id varchar2(128 char) not null,
    status varchar2(32 char) not null,
    system_template clob,
    user_template clob,
    metadata_json clob,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint pk_agent_prompt_template primary key (prompt_id, version)
);

create index idx_agent_prompt_template_agent
    on agent_prompt_template (agent_id, status, version);

create table agent_approval_request (
    approval_id varchar2(64 char) not null,
    execution_id varchar2(64 char) not null,
    agent_id varchar2(128 char) not null,
    agent_version varchar2(64 char),
    tenant_id varchar2(128 char),
    requested_by varchar2(128 char),
    status varchar2(32 char) not null,
    reason clob,
    metadata_json clob,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone,
    decided_at timestamp with time zone,
    decided_by varchar2(128 char),
    constraint pk_agent_approval_request primary key (approval_id)
);

create index idx_agent_approval_execution
    on agent_approval_request (execution_id, status, created_at);

create index idx_agent_approval_tenant
    on agent_approval_request (tenant_id, status, created_at);

create table agent_pending_command (
    execution_id varchar2(64 char) not null,
    agent_id varchar2(128 char) not null,
    agent_version varchar2(64 char),
    input_type varchar2(512 char) not null,
    input_json clob not null,
    options_json clob,
    tenant_id varchar2(128 char),
    actor_id varchar2(128 char),
    correlation_id varchar2(128 char),
    requested_at timestamp with time zone,
    context_attributes_json clob,
    callback_url varchar2(1000 char),
    created_at timestamp with time zone not null,
    constraint pk_agent_pending_command primary key (execution_id)
);

create index idx_agent_pending_command_agent
    on agent_pending_command (agent_id, agent_version, created_at);

create index idx_agent_pending_command_tenant
    on agent_pending_command (tenant_id, created_at);


create table agent_async_queue_command (
    execution_id varchar2(64 char) not null,
    agent_id varchar2(128 char) not null,
    agent_version varchar2(64 char),
    input_type varchar2(512 char) not null,
    input_json clob not null,
    options_json clob,
    tenant_id varchar2(128 char),
    actor_id varchar2(128 char),
    correlation_id varchar2(128 char),
    requested_at timestamp with time zone,
    context_attributes_json clob,
    callback_url varchar2(1000 char),
    created_at timestamp with time zone not null,
    constraint pk_agent_async_queue_command primary key (execution_id)
);

create index idx_agent_async_queue_created
    on agent_async_queue_command (created_at);

create index idx_agent_async_queue_tenant
    on agent_async_queue_command (tenant_id, created_at);
create table agent_evaluation_result (
    evaluation_id varchar2(64 char) not null,
    dataset_name varchar2(256 char) not null,
    status varchar2(32 char) not null,
    total_count number(10) not null,
    passed_count number(10) not null,
    failed_count number(10) not null,
    cases_json clob,
    evaluated_at timestamp with time zone not null,
    constraint pk_agent_evaluation_result primary key (evaluation_id)
);

create index idx_agent_evaluation_result_dataset
    on agent_evaluation_result (dataset_name, evaluated_at);

create index idx_agent_evaluation_result_status
    on agent_evaluation_result (status, evaluated_at);




create table agent_checkpoint (
    execution_id varchar2(64 char) not null,
    step_name varchar2(200 char) not null,
    step_index number(10) not null,
    result_json clob,
    completed_at timestamp with time zone not null,
    constraint pk_agent_checkpoint primary key (execution_id, step_name)
);

create index idx_agent_checkpoint_execution
    on agent_checkpoint (execution_id, step_index);

create table agent_workflow_budget (
    workflow_id varchar2(64 char) not null,
    used_agent_invocations number(10) default 0 not null,
    used_tool_calls number(10) default 0 not null,
    used_cost_usd number(19, 6) default 0 not null,
    updated_at timestamp with time zone not null,
    version number(19) default 0 not null,
    constraint pk_agent_workflow_budget primary key (workflow_id)
);

create table agent_evaluation_dataset (
    dataset_name varchar2(200 char) not null,
    description varchar2(1000 char),
    examples_json clob,
    metadata_json clob,
    updated_at timestamp with time zone not null,
    constraint pk_agent_evaluation_dataset primary key (dataset_name)
);
