package ai.qubere.agent.core;

public enum AgentErrorCode {
    NOT_FOUND,
    AGENT_NOT_FOUND,
    AGENT_DISABLED,
    AUTHORIZATION_DENIED,
    GUARDRAIL_BLOCKED,
    VALIDATION_FAILED,
    EXECUTION_FAILED,
    AI_PROVIDER_UNAVAILABLE,
    AI_PROVIDER_FAILURE,
    GOVERNANCE_LIMIT_EXCEEDED,
    TOOL_NOT_FOUND,
    TOOL_NOT_ALLOWED,
    TOOL_APPROVAL_REQUIRED,
    TOOL_FAILED,
    TIMEOUT
}
