-- Qubere Agent Platform Phase 1 manual DDL for Oracle.
-- Execute manually before running agent-app with spring.jpa.hibernate.ddl-auto=validate.
-- Oracle does not support create table if not exists; run once per schema.

create table agent_execution_record (
    execution_id varchar2(64 char) not null,
    agent_id varchar2(128 char) not null,
    agent_version varchar2(64 char) not null,
    tenant_id varchar2(128 char),
    actor_id varchar2(128 char),
    status varchar2(32 char) not null,
    input_json clob,
    output_json clob,
    error_message clob,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint pk_agent_execution_record primary key (execution_id)
);

create index idx_agent_execution_record_agent
    on agent_execution_record (agent_id, agent_version);

create index idx_agent_execution_record_tenant
    on agent_execution_record (tenant_id, created_at);

create table agent_tool_audit_event (
    id number generated by default as identity not null,
    execution_id varchar2(64 char) not null,
    tenant_id varchar2(128 char),
    actor_id varchar2(128 char),
    tool_name varchar2(128 char) not null,
    status varchar2(32 char) not null,
    message varchar2(1000 char),
    metadata_json clob,
    occurred_at timestamp with time zone not null,
    constraint pk_agent_tool_audit_event primary key (id)
);

create index idx_agent_tool_audit_execution
    on agent_tool_audit_event (execution_id, occurred_at);

create index idx_agent_tool_audit_tenant
    on agent_tool_audit_event (tenant_id, occurred_at);

create table agent_prompt_template (
    prompt_id varchar2(128 char) not null,
    version varchar2(64 char) not null,
    agent_id varchar2(128 char) not null,
    status varchar2(32 char) not null,
    system_template clob,
    user_template clob,
    metadata_json clob,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint pk_agent_prompt_template primary key (prompt_id, version)
);

create index idx_agent_prompt_template_agent
    on agent_prompt_template (agent_id, status, version);

create table agent_approval_request (
    approval_id varchar2(64 char) not null,
    execution_id varchar2(64 char) not null,
    agent_id varchar2(128 char) not null,
    agent_version varchar2(64 char),
    tenant_id varchar2(128 char),
    requested_by varchar2(128 char),
    status varchar2(32 char) not null,
    reason clob,
    metadata_json clob,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone,
    decided_at timestamp with time zone,
    decided_by varchar2(128 char),
    constraint pk_agent_approval_request primary key (approval_id)
);

create index idx_agent_approval_execution
    on agent_approval_request (execution_id, status, created_at);

create index idx_agent_approval_tenant
    on agent_approval_request (tenant_id, status, created_at);

create table agent_pending_command (
    execution_id varchar2(64 char) not null,
    agent_id varchar2(128 char) not null,
    agent_version varchar2(64 char),
    input_type varchar2(512 char) not null,
    input_json clob not null,
    options_json clob,
    tenant_id varchar2(128 char),
    actor_id varchar2(128 char),
    correlation_id varchar2(128 char),
    requested_at timestamp with time zone,
    context_attributes_json clob,
    callback_url varchar2(1000 char),
    created_at timestamp with time zone not null,
    constraint pk_agent_pending_command primary key (execution_id)
);

create index idx_agent_pending_command_agent
    on agent_pending_command (agent_id, agent_version, created_at);

create index idx_agent_pending_command_tenant
    on agent_pending_command (tenant_id, created_at);

create table agent_evaluation_result (
    evaluation_id varchar2(64 char) not null,
    dataset_name varchar2(256 char) not null,
    status varchar2(32 char) not null,
    total_count number(10) not null,
    passed_count number(10) not null,
    failed_count number(10) not null,
    cases_json clob,
    evaluated_at timestamp with time zone not null,
    constraint pk_agent_evaluation_result primary key (evaluation_id)
);

create index idx_agent_evaluation_result_dataset
    on agent_evaluation_result (dataset_name, evaluated_at);

create index idx_agent_evaluation_result_status
    on agent_evaluation_result (status, evaluated_at);
